- _data/authors.yml
> Add authors

- pages/08_kontakt.md
- pages/status.md
> add page Kontakt from old website

- pages/08_kontakt.md
> 21 kontaktpage discord link broken

- _includes/default/footer.liquid
- _sass/includes/_footer.scss
- pages/08_kontakt.md
- pages/09_impressum.md
- pages/10_datenschutz.md
Added links to footer
- Kontakt
- Impressum (removed from navbar)
- Datenschutz (removed from navbar)
> Adds links in footer

- _data/language.yml
- _includes/blog/post_info.liquid
Deutscher Datumsformat mit deutschen Monatsnamen
> Change date format to german with german month names

- .github/workflows/jekyll-gh-pages.yml
This reverts commit 293432f8a49ac9cf94d59f959bfe27923cafbb6a, reversing changes made to 130a25515bb2c1a6a00abbe60e4c6d4ecfb1690e.
> Revert "Merge pull request #46 from netz39/hotfix_jekyll-build-action"

- _events/2023-11-22_workshop-git.md
> fix: update git workshop event

- _events/2023-10-30_loetworkshop.md
- _events/2023-11-09_loetworkshop.md
- _events/2023-11-13_loetworkshop.md
- assets/img/events/loetworkshop.jpg
Add Mail Adress and a picture to the soldering workshops
> Add Mail Adress and a picture to the soldering workshops

- _posts/2023/2023-10-31-halloween.md
- assets/img/post-img/2023/nOOds-fledermaeuse.jpeg
- assets/img/post-img/2023/nOOds-fledermaus.jpeg
- assets/img/post-img/2023/nOOds-geist.jpeg
- assets/img/post-img/2023/nOOds-hexenhut.jpeg
- assets/img/post-img/2023/nOOds-render.png
Wir müssen mal die Blogeinträge von 2021 und 2019 von der Startseite drängen 😄
> Add Blogpost Halloween Deko

- _includes/default/navbar.liquid
- _sass/includes/_navbar.scss
Make the space status picture rounded to visually match the other icons.
> Make the space status picture rounded

- _sass/includes/_navbar.scss
> Match the edges of the status image with its content

- pages/08_kontakt.md
Alle anderen Überschriften sind auch Level2 Headlines
> Change Kontakt Headlines

- pages/09_impressum.md
> Update Spenden text with link to subpage

- _includes/default/navbar.liquid
- _sass/base/_global.scss
Use pointer cursor when hovering over theme toggle button
> Fix theme toggle button label

- tools/generate_stammtisch_events.py
und ein +x gibt's auch noch dazu
> Fix: add python3 shebang

- _events/2024/2024-04-05_softwerke_stammtisch.md
> Events/2024 04 05 softwerke stammtisch.md

- _includes/default/navbar.liquid
> Add lazy loading to space API image

- _includes/default/tags_list.liquid
siehe https://github.com/netz39/www.netz39.de/issues/161
> fix(tags_list): replace page.baseurl with page.url

- _events/2025/2025-07-05_naehworkshop_totoro.md
Event für Nähworkshop von Josi im Juli
> chore: add 'totoro naehworkshop to events'

- _events/2025/2025-07-05_naehworkshop_totoro.md
> fix: 'totoro naehworkshop' date changed

- _config.yml
Gemäß
* https://redmine.n39.eu/issues/1186
* https://redmine.n39.eu/issues/1177
> Passe Vorstandsmitglieder an

- _data/menu.yml
- pages/events.md
- pages/kontakt.md
- pages/mitgliedschaft.md
- pages/spenden.md
Ich habe nun mal für die restlichen Einträge in der Nav-Bar die für mich passenden Icons rausgesucht.
> Add icons to all entrys in nav bar

- _includes/default/sponsors_banner.liquid
- _layouts/home.liquid
- _sass/includes/_sponsors_banner.scss
for images see https://github.com/netz39/www.netz39.de/issues/175
> fix(sponsors_banner): fix disappearing logo on light mode

- _events/2025/discord-event-1328749312980553879.md
Adding `_events/2025/discord-event-1328749312980553879.md` via posthorn.
> feat[_events]: add _events/2025/discord-event-1328749312980553879.md

- _events/2025/discord-event-1376841400510971904.md
Adding `_events/2025/discord-event-1376841400510971904.md` via posthorn.
> feat[_events]: add _events/2025/discord-event-1376841400510971904.md

- _events/2025/discord-event-1415407086317342792.md
Adding `_events/2025/discord-event-1415407086317342792.md` via posthorn.
> feat[_events]: add _events/2025/discord-event-1415407086317342792.md

- _events/2025/discord-event-1415406548922142741.md
Adding `_events/2025/discord-event-1415406548922142741.md` via posthorn.
> feat[_events]: add _events/2025/discord-event-1415406548922142741.md

- _events/2025/discord-event-1415961159550505041.md
Adding `_events/2025/discord-event-1415961159550505041.md` via posthorn.
> feat[_events]: add _events/2025/discord-event-1415961159550505041.md

- _events/2025/discord-event-1415962689842188298.md
Adding `_events/2025/discord-event-1415962689842188298.md` via posthorn.
> feat[_events]: add _events/2025/discord-event-1415962689842188298.md

- _events/2025/discord-event-1415958723137896458.md
Adding `_events/2025/discord-event-1415958723137896458.md` via posthorn.
> feat[_events]: add _events/2025/discord-event-1415958723137896458.md

- _config.yml
- pages/linux.md
- type-on-strap.gemspec
This endpoint is meant to redirect to the latest linux install party.
> feat(linux.md): add redirect endpoint
